name: "CI"

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  # Run unit tests
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.23.4'

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ffmpeg
          ffmpeg -version
          ffprobe -version

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
          cache-dependency-path: "**/*.sum"

      

      - name: Run go vet
        run: |
          go vet ./...

      

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html
          if-no-files-found: error

  # Build binaries
  build:
    needs: test
    name: Build ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        go:
          - '1.23.4'
        goos:
          - linux
          - windows
          - darwin
        goarch:
          - "386"
          - amd64
          - arm
          - arm64
        exclude:
          - goos: darwin
            goarch: arm
          - goos: darwin
            goarch: "386"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # 编译本身不运行 ffmpeg，因此这里不需要安装 FFmpeg

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
          cache-dependency-path: "**/*.sum"

      - name: Set build environment
        shell: bash
        run: |
          echo "BUILD_TIME=$(date --rfc-3339=seconds)" >> "$GITHUB_ENV"

          if [ "${{ matrix.goos }}" = "windows" ]; then
            echo "BINARY_NAME=DDBOT.exe" >> "$GITHUB_ENV"
          else
            echo "BINARY_NAME=DDBOT" >> "$GITHUB_ENV"
          fi

      - name: Build binary file
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: "0"
        run: |
          go build \
            -trimpath \
            -o "${{ env.BINARY_NAME }}" \
            -ldflags '-w -s -X "github.com/cnxysoft/DDBOT-WSa/lsp.BuildTime=${{ env.BUILD_TIME }}" -X "github.com/cnxysoft/DDBOT-WSa/lsp.CommitId=${{ github.sha }}"' \
            github.com/cnxysoft/DDBOT-WSa/cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ !github.head_ref }}
        with:
          name: ${{ matrix.goos }}_${{ matrix.goarch }}
          path: ${{ env.BINARY_NAME }}
          if-no-files-found: error
